### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by sanvila** [xsteadfastx/jitsiexporter#4]
Hi. Would be possible to put this useful program under a free (i.e. libre) license?
I'd like to see it packaged for Debian some day, but that's not possible unless
it has a valid free software license. Thanks.

**Comment by xsteadfastx** [comment]
yes sure... i want it to be MIT license. will see how i can do that.

**Comment by xsteadfastx** [comment]
done 9efb1042e3be4cc4b90562c2aad1e0bdf0d89974 :+1: :heart:
