### ISSUE TITLE
starting container process caused "exec: \"/bin/jitsiexporter\": stat /bin/jitsiexporter: no such file or directory"

### ISSUE THREAD

**Issue by ginkel** [xsteadfastx/jitsiexporter#8]
The exporter version that has been published around 1 h ago is failing to start as the entry point / cmd seems to be mising:

```
$ docker run -it --rm quay.io/xsteadfastx/jitsiexporter:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/bin/jitsiexporter\": stat /bin/jitsiexporter: no such file or directory": unknown.
```

**Comment by xsteadfastx** [comment]
On Wed Oct 7, 2020 at 8:23 AM CEST, Thilo-Alexander Ginkel wrote:
> The exporter version that has been published around 1 h ago is failing
> to start as the entry point / cmd seems to be mising:
>
> ```
> $ docker run -it --rm quay.io/xsteadfastx/jitsiexporter:latest
> docker: Error response from daemon: OCI runtime create failed:
> container_linux.go:349: starting container process caused "exec:
> \"/bin/jitsiexporter\": stat /bin/jitsiexporter: no such file or
> directory": unknown.

can pull a fresh version? i converted everything to goreleaser and had
to work a little around my CI setup. should work now!

**Comment by ginkel** [comment]
LGTM, thanks for the speedy fix!
